Step UI test
AnnaNikolya/TestRailDiplom pull request #1
Opened 2022-01-23 18:31 UTC by AnnaNikolya

Создано 7 тестов

2022-01-24 14:40 UTC, vchesnakoutest requested changes

2022-01-24 14:40 UTC, vchesnakoutest commented on src/main/java/constants/IConstants.java
> +//Password: k2Jntx.y5gHK0hdqKWbH
закоменченный код лучше не оставлять

2022-01-24 14:40 UTC, vchesnakoutest commented on src/main/java/pages/SignUpPage.java
> +        buttonTryTest.scrollIntoView(SCROLL_INTO_CENTER_SCRIPT).click();
это действие необходимо делать непосредственно в методе вместе с кликом из-за которого у тебя падал тест

2022-01-24 14:40 UTC, vchesnakoutest commented on src/main/java/pages/SignUpPage.java
> +//    }
закоменченный код лучше не оставлять

2022-01-24 14:40 UTC, vchesnakoutest commented on src/main/java/pages/TestRailPage.java
> +
1 лишний отступ

2022-01-24 14:40 UTC, vchesnakoutest commented on src/main/java/pages/TestRailPage.java
> +        $(MISTAKE_TEXT).shouldHave(Condition.visible);// shouldHave(text(" "));
закоменченный код лучше не оставлять

2022-01-24 14:40 UTC, vchesnakoutest commented on src/main/java/steps/LoginSteps.java
> +        open("https://diplontestrail1234.testrail.io/");
у тебя этот урл уже открывается через метод openDashboardPage в LoginPage. Зачем тут ещё раз дублируешь эту логику?

2022-01-24 14:40 UTC, vchesnakoutest commented on src/main/java/steps/LoginSteps.java
> +    }
степы не надо делать для 1 действия. Степы нужны, когда мы хотим объеденить в себе более 2,3 действий вместе.

2022-01-24 14:40 UTC, vchesnakoutest commented on src/test/java/LoginTest.java
> +        loginPage.login(EMAIL, PASSWORD);
нету ассерта

2022-01-24 14:40 UTC, vchesnakoutest commented on src/test/java/SignUpTest.java
> +        signUpPage.enterValue("diplontestrail", "YourFistName", "YourLastName",
нету ассерта (проверь также все остальные тесты))

2022-01-24 16:54 UTC, AnnaNikolya commented on src/main/java/pages/TestRailPage.java
> +
Отредактирована

2022-01-24 16:55 UTC, AnnaNikolya commented on src/main/java/pages/TestRailPage.java
> +
Отредактировано

2022-01-24 16:56 UTC, AnnaNikolya commented on src/main/java/pages/TestRailPage.java
> +        $(MISTAKE_TEXT).shouldHave(Condition.visible);// shouldHave(text(" "));
Удалено

2022-01-24 17:01 UTC, AnnaNikolya commented on src/main/java/steps/LoginSteps.java
> +        open("https://diplontestrail1234.testrail.io/");
Удалено, экспериментировала с запуском страницы, что бы не логинится каждый раз

2022-01-24 17:08 UTC, AnnaNikolya commented on src/main/java/constants/IConstants.java
> +//Password: k2Jntx.y5gHK0hdqKWbH
Удалено

2022-01-24 17:13 UTC, AnnaNikolya commented on src/main/java/pages/SignUpPage.java
> +        buttonTryTest.scrollIntoView(SCROLL_INTO_CENTER_SCRIPT).click();
Действие перенесено в метод enterValue, где после нажатия выполняется заполнение всех полей и регистрация

2022-01-24 17:13 UTC, AnnaNikolya commented on src/main/java/pages/SignUpPage.java
> +//    }
Удалено

2022-01-27 15:40 UTC, AnnaNikolya commented on src/test/java/SignUpTest.java
> +        signUpPage.enterValue("diplontestrail", "YourFistName", "YourLastName",
Добавлены

2022-01-27 15:40 UTC, merged