Step UI test
AnnaNikolya/TestRailDiplom pull request #2
Opened 2022-01-27 15:51 UTC by AnnaNikolya

Create page: Admin, Dashboard, Header, MySettings, ProjectsP. Add Assert in Test

2022-01-28 21:00 UTC, vchesnakoutest requested changes

2022-01-28 21:00 UTC, vchesnakoutest commented on src/main/java/pages/DashboardPage.java
> +    String CHOOSE_PROJECT = "//a[contains(text(),'Test 3')]";
Test 3 - это надо передавать из тестов через параметр. В данном случае это хардкод данных.

2022-01-28 21:00 UTC, vchesnakoutest commented on src/main/java/pages/ProjectsPage.java
> +        return null;
зачем return null? если ничего возвращать не надо делай метод void

2022-01-28 21:00 UTC, vchesnakoutest commented on src/main/java/pages/ProjectsPage.java
> +    public String textMistakeCreate() {
getMistakeText

2022-01-28 21:00 UTC, vchesnakoutest commented on src/main/java/pages/ProjectsPage.java
> +    public String contentTextInHeader() {
getContentTextInHeader

2022-01-28 21:00 UTC, vchesnakoutest commented on src/main/java/pages/ProjectsPage.java
> +    public String contentTextAboutDelete() {
getContentTextInHeader

2022-01-28 21:00 UTC, vchesnakoutest commented on src/main/java/pages/TestRailPage.java
> +//    }
закоменченный код надо удалять

2022-01-29 14:57 UTC, AnnaNikolya commented on src/main/java/pages/DashboardPage.java
> +    String CHOOSE_PROJECT = "//a[contains(text(),'Test 3')]";
Переделано, передаются данные через параметр

2022-01-29 18:13 UTC, AnnaNikolya commented on src/main/java/pages/ProjectsPage.java
> +        return null;
Все исправлено

2022-01-29 18:14 UTC, AnnaNikolya commented on src/main/java/pages/ProjectsPage.java
> +    public String textMistakeCreate() {
Отредактирована

2022-01-29 18:15 UTC, AnnaNikolya commented on src/main/java/pages/ProjectsPage.java
> +    public String contentTextInHeader() {
Отредактирована

2022-01-29 18:15 UTC, AnnaNikolya commented on src/main/java/pages/ProjectsPage.java
> +    public String contentTextAboutDelete() {
Отредактирована

2022-01-29 18:23 UTC, AnnaNikolya commented on src/main/java/pages/TestRailPage.java
> +//    }
Удалено

2022-01-29 18:24 UTC, merged